// Certification catalog for the Learning tab. Checked against Microsoft Learn and AWS in September 2026.
// Edit freely: order of PLAN is the roadmap; OPTIONAL shows under "Also worth knowing".
//
// Salary figures: Skillsoft IT Skills and Salary report (2024 survey, published April 2025), average US salary of
// people who hold the cert. Small US samples, and it reflects the jobs holders already have, not a raise the cert guarantees.

const ML = 'https://learn.microsoft.com/en-us/credentials/certifications';
const SANDBOX = { label: 'Exam sandbox (try the interface)', url: 'https://go.microsoft.com/fwlink/?linkid=2226877' };

export const PRICES_NOTE = 'US prices: Microsoft fundamentals $99, associate and expert $165. Retakes cost the full fee.';

export const CERTS = {
  'ai-901': {
    code: 'AI-901',
    name: 'Azure AI Fundamentals',
    vendor: 'Microsoft',
    level: 'Fundamentals',
    kind: 'cert',
    cost: 99,
    format: '45-minute exam, pass mark 700',
    validity: 'Never expires',
    renewYearly: false,
    estHours: 20,
    summary: 'AI concepts and building simple AI solutions with Microsoft Foundry. Replaced AI-900 in April 2026.',
    why: 'A quick first win that proves AI literacy and gets the Azure AI vocabulary in place before the harder exams. The course expects basic Python syntax, so it also shows early where coding practice is needed.',
    impact: 'Low on its own; strong as a first line on the résumé. Holders of the AI-900 version averaged about $131K (US, Skillsoft).',
    roles: ['Any IT role touching Copilot or Azure AI'],
    links: [
      { label: 'Exam page', url: `${ML}/exams/ai-901/` },
      { label: 'Study guide', url: 'https://aka.ms/AI-901-StudyGuide' },
      { label: 'Free course: Introduction to AI in Azure', url: 'https://learn.microsoft.com/en-us/training/courses/ai-901t00' },
      { label: 'Free practice assessment', url: 'https://aiskillsnavigator.microsoft.com/credentials/cert-83587e0a0754cfee561ade3e27d9fa1cdaf15ae03be52d2413b2b858d1b4eda4' },
      SANDBOX,
    ],
  },
  'az-104': {
    code: 'AZ-104',
    name: 'Azure Administrator Associate',
    vendor: 'Microsoft',
    level: 'Associate',
    kind: 'cert',
    cost: 165,
    format: '100-minute exam with interactive tasks',
    validity: '1 year, renews free online',
    renewYearly: true,
    estHours: 70,
    summary: 'Identities and governance, storage, compute, virtual networking and monitoring in Azure.',
    why: 'The core cloud credential and the most common Azure cert in job postings. Your Entra and Intune work covers part of the identity section, and it is the prerequisite for the architect expert cert.',
    impact: 'High. Opens Azure/cloud administrator and cloud support engineer roles. Holders averaged about $149K (US, Skillsoft).',
    roles: ['Cloud administrator', 'Azure administrator', 'Cloud support engineer'],
    links: [
      { label: 'Certification page', url: `${ML}/azure-administrator/` },
      { label: 'Study guide', url: 'https://aka.ms/AZ104-StudyGuide' },
      { label: 'Free practice assessment', url: `${ML}/azure-administrator/practice/assessment?assessment-type=practice&assessmentId=21&practice-assessment-type=certification` },
      { label: 'Exam prep videos', url: 'https://aka.ms/AZ104-ExamPrep' },
      SANDBOX,
    ],
  },
  python: {
    code: 'Skill',
    name: 'Python basics',
    vendor: 'Microsoft Learn',
    level: 'Skill',
    kind: 'skill',
    cost: 0,
    format: '44 short videos, then practice',
    validity: 'No exam',
    renewYearly: false,
    estHours: 20,
    summary: 'Variables, functions, loops, working with APIs and packages: enough to read and write the code in AI-103 labs.',
    why: 'AI-103 expects experience building apps in Python. A few weeks of basics first makes that exam far easier, and it is useful for IT scripting too.',
    impact: 'Unlocks the AI developer track; no credential by itself.',
    roles: [],
    links: [
      { label: 'Python for Beginners (Microsoft video series)', url: 'https://learn.microsoft.com/en-us/shows/intro-to-python-development/' },
      { label: 'More Python for Beginners', url: 'https://learn.microsoft.com/en-us/shows/more-python-for-beginners/' },
    ],
  },
  'ai-103': {
    code: 'AI-103',
    name: 'Azure AI Apps and Agents Developer Associate',
    vendor: 'Microsoft',
    level: 'Associate',
    kind: 'cert',
    cost: 165,
    format: '120-minute exam with interactive tasks',
    validity: '1 year, renews free online',
    renewYearly: true,
    estHours: 60,
    summary: 'Build generative AI and agent solutions, vision, text analysis and information extraction on Azure. Replaced AI-102 (retired June 30, 2026).',
    why: 'This is the AI engineer credential on the Cloud & AI path, and the one that moves you from running systems to building AI solutions.',
    impact: 'High. Aimed at AI engineer and AI developer roles. Holders of AI-102, its predecessor, averaged about $159K (US, Skillsoft).',
    roles: ['AI engineer', 'AI developer', 'Solutions engineer (AI)'],
    links: [
      { label: 'Exam page', url: `${ML}/exams/ai-103/` },
      { label: 'Study guide', url: 'https://aka.ms/AI103-StudyGuide' },
      { label: 'Free practice assessment', url: 'https://aiskillsnavigator.microsoft.com/credentials/cert-3fb198f57997226a824aa5f52a1a22af9a4597941b2288ed39371c7a9e6bd7c9' },
      SANDBOX,
    ],
  },
  'az-305': {
    code: 'AZ-305',
    name: 'Azure Solutions Architect Expert',
    vendor: 'Microsoft',
    level: 'Expert',
    kind: 'cert',
    cost: 165,
    format: '100-minute exam; requires AZ-104 first',
    validity: '1 year, renews free online',
    renewYearly: true,
    estHours: 60,
    summary: 'Designing identity, governance, data, business continuity and infrastructure solutions.',
    why: 'The senior step once AZ-104 and some real Azure work are behind you. Pairs with AI-103 for AI solution architect roles.',
    impact: 'High for senior roles. Holders averaged about $145K (US, Skillsoft).',
    roles: ['Cloud architect', 'Solutions architect'],
    links: [{ label: 'Certification page', url: `${ML}/azure-solutions-architect/` }],
  },

  // ---- optional ----
  'az-900': {
    code: 'AZ-900',
    name: 'Azure Fundamentals',
    vendor: 'Microsoft',
    level: 'Fundamentals',
    kind: 'cert',
    cost: 99,
    format: '45-minute exam',
    validity: 'Never expires',
    renewYearly: false,
    estHours: 12,
    summary: 'Cloud concepts, core Azure services, management and governance.',
    why: 'Skippable on this path: AI-901 already gives you a fundamentals badge and AZ-104 covers everything here in more depth. Worth it only as a warm-up if AZ-104 feels like too big a jump.',
    impact: 'Low. Holders averaged about $118K (US, Skillsoft).',
    roles: [],
    links: [
      { label: 'Certification page', url: `${ML}/azure-fundamentals/` },
      { label: 'Study guide', url: 'https://aka.ms/AZ900-StudyGuide' },
    ],
  },
  'sc-300': {
    code: 'SC-300',
    name: 'Identity and Access Administrator Associate',
    vendor: 'Microsoft',
    level: 'Associate',
    kind: 'cert',
    cost: 165,
    format: '100-minute exam',
    validity: '1 year, renews free online',
    renewYearly: true,
    estHours: 35,
    summary: 'Entra ID identities, authentication, access management and identity governance.',
    why: 'A quick win from your day job. You already administer Entra, so it would take far fewer hours than its size suggests. Take it if you want an identity credential alongside the cloud path.',
    impact: 'Medium. Strong for identity and security roles.',
    roles: ['Identity engineer', 'IAM administrator'],
    links: [
      { label: 'Certification page', url: `${ML}/identity-and-access-administrator/` },
      { label: 'Study guide', url: 'https://aka.ms/sc300-StudyGuide' },
    ],
  },
  'md-102': {
    code: 'MD-102',
    name: 'Endpoint Administrator Associate',
    vendor: 'Microsoft',
    level: 'Associate',
    kind: 'cert',
    cost: 165,
    format: '100-minute exam',
    validity: '1 year, renews free online',
    renewYearly: true,
    estHours: 30,
    summary: 'Intune, Autopilot, device and app management, endpoint security.',
    why: 'Mostly what you do at work with Intune. Less aligned with the Cloud & AI direction, but a fast credential for your current role.',
    impact: 'Medium for endpoint and desktop engineering roles.',
    roles: ['Endpoint administrator', 'Desktop engineer'],
    links: [
      { label: 'Certification page', url: `${ML}/modern-desktop/` },
      { label: 'Study guide', url: 'https://aka.ms/md102-StudyGuide' },
    ],
  },
  'aws-aif': {
    code: 'AIF-C01',
    name: 'AWS Certified AI Practitioner',
    vendor: 'AWS',
    level: 'Foundational',
    kind: 'cert',
    cost: 100,
    format: '90-minute exam',
    validity: '3 years',
    renewYearly: false,
    estHours: 20,
    summary: 'AI, ML and generative AI concepts on AWS.',
    why: 'Only if you want multi-cloud breadth later. Staying Microsoft-first matches where your experience is.',
    impact: 'Low to medium; breadth rather than depth.',
    roles: [],
    links: [{ label: 'Certification page', url: 'https://aws.amazon.com/certification/certified-ai-practitioner/' }],
  },
  'ai-200': {
    code: 'AI-200',
    name: 'Azure AI Cloud Developer Associate',
    vendor: 'Microsoft',
    level: 'Associate',
    kind: 'cert',
    cost: 165,
    format: '120-minute exam',
    validity: '1 year, renews free online',
    renewYearly: true,
    estHours: 60,
    summary: 'Containerized AI back ends, Azure data services and vector databases, messaging, monitoring. Replaced AZ-204.',
    why: 'For a developer-heavy direction after AI-103. Needs solid Python and SDK experience.',
    impact: 'High for developer roles. Holders of AZ-204, its predecessor, averaged about $157K (US, Skillsoft).',
    roles: ['Cloud developer', 'AI back-end developer'],
    links: [
      { label: 'Exam page', url: `${ML}/exams/ai-200/` },
      { label: 'Study guide', url: 'https://aka.ms/AI200-StudyGuide' },
    ],
  },
  'ai-300': {
    code: 'AI-300',
    name: 'Machine Learning Operations Engineer Associate',
    vendor: 'Microsoft',
    level: 'Associate',
    kind: 'cert',
    cost: 165,
    format: '120-minute exam',
    validity: '1 year, renews free online',
    renewYearly: true,
    estHours: 70,
    summary: 'MLOps and GenAIOps: model lifecycle, deployment, evaluation and monitoring. Replaced DP-100.',
    why: 'Specialist. Only if you move toward data science or ML platform work.',
    impact: 'Niche but well paid.',
    roles: ['MLOps engineer'],
    links: [{ label: 'Exam page', url: `${ML}/exams/ai-300/` }],
  },
  'applied-ai-security': {
    code: 'Applied Skill',
    name: 'Secure AI solutions in the cloud',
    vendor: 'Microsoft',
    level: 'Applied Skills',
    kind: 'cert',
    cost: 0,
    format: 'Free, lab-based assessment',
    validity: 'Never expires',
    renewYearly: false,
    estHours: 10,
    summary: 'Configure security and guardrails for AI services with Defender for Cloud and Microsoft Foundry.',
    why: 'Free and hands-on. A good small credential between AI-901 and AZ-104 that ties your security background to AI.',
    impact: 'Low to medium; free proof of hands-on skill.',
    roles: [],
    links: [{ label: 'Browse Applied Skills', url: 'https://learn.microsoft.com/en-us/credentials/browse/?credential_types=applied%20skills' }],
  },
};

export const PLAN = ['ai-901', 'az-104', 'python', 'ai-103', 'az-305'];
export const OPTIONAL = ['applied-ai-security', 'sc-300', 'az-900', 'md-102', 'aws-aif', 'ai-200', 'ai-300'];

export const TIPS = [
  ['One exam at a time', 'At 3–5 hours a week, switching between two certs means neither gets finished. Side credentials fit in the gaps between main ones.'],
  ['Free material first', 'Each Microsoft exam has a free Learn course and study guide. Paid courses are optional; the free practice assessment is not.'],
  ['Take the practice assessment early', 'Do it in week one to see the gaps, then again near the end. Book the exam once you score 80% or better twice in a row (a rule of thumb, not a Microsoft requirement).'],
  ['Book 3–4 weeks out', 'A booked date turns "studying" into a deadline. Mark it here and it shows on Home with a countdown.'],
  ['Get hands-on', 'AZ-104 and AI-103 include interactive tasks. Do the labs in a free Azure account, not just the reading.'],
  ['Ask about reimbursement', 'Check with your manager or HR whether Alliant covers exam fees or training time before you pay.'],
  ['Watch for free vouchers', 'Microsoft ran a free-voucher AI Skills Fest in June 2026 and a 50%-off challenge in early 2026. Similar events come back; check before booking.'],
  ['Renew for free', 'Associate and expert certs expire yearly. A free, open-book renewal assessment opens 6 months before expiry. This tab reminds you on Home.'],
];

export const SOURCES = [
  { label: 'Microsoft Learn: certification and exam pages', url: 'https://learn.microsoft.com/en-us/credentials/' },
  { label: 'Microsoft Learn: renewing certifications', url: `${ML}/renew-your-microsoft-certification` },
  { label: 'Microsoft certification changes in 2026 (Vlad Catrinescu)', url: 'https://vladtalkstech.com/microsoft-learning-and-credential-news/microsoft-certification-retirements-2026/' },
  { label: 'Skillsoft: top-paying Microsoft certifications', url: 'https://www.skillsoft.com/blog/top-paying-microsoft-certifications' },
  { label: 'AWS Certified AI Practitioner', url: 'https://aws.amazon.com/certification/certified-ai-practitioner/' },
];
