// The demo's recipe box: a few everyday dishes, written for the demo. No photos, so each shows its drawn plate.
import { normalizeRecipe } from './recipebox-logic.js';
import { addDays } from './budget-logic.js';

const RECIPES = [
  {
    id: 'demo-miso-salmon',
    title: 'Miso-glazed salmon',
    subtitle: 'with sesame rice and charred broccoli',
    source: 'Mine',
    servings: 4,
    minutes: 30,
    nutrition: [560, 38, 52, 20, 5, 11, 980],
    tags: ['Weeknight', 'Fish'],
    fav: 1,
    made: 6,
    ingredients: [
      '4 salmon fillets (about 6 oz each)',
      '1½ cups jasmine rice',
      '1 head broccoli (cut into florets)',
      '3 tbsp white miso',
      '2 tbsp mirin',
      '1 tbsp honey',
      '1 tbsp soy sauce',
      '2 scallions (thinly sliced)',
      '1 tbsp sesame seeds',
      { item: 'Sesame oil', amount: '2 tsp', pantry: true },
      { item: 'Neutral oil', amount: '1 tbsp', pantry: true },
    ],
    steps: [
      { title: 'Rice', text: 'Rinse the rice, then simmer it covered in [[2¼ cups]] water for 15 minutes. Rest 10 minutes off the heat and fluff with the sesame oil.' },
      { title: 'Glaze', text: 'Whisk the miso, mirin, honey and soy sauce until smooth.' },
      { title: 'Broil', text: 'Heat the broiler. Brush the salmon with most of the glaze and broil 6–8 minutes, until caramelized at the edges and just opaque in the middle.' },
      { title: 'Broccoli', text: 'Meanwhile, sear the broccoli in the neutral oil over high heat for 5 minutes, until charred in spots. Toss with the last of the glaze.' },
      { title: 'Serve', text: 'Spoon rice into bowls, add broccoli and salmon, and finish with scallions and sesame seeds.' },
    ],
    notes: 'Thicker fillets need a minute or two more. The glaze keeps a week in the fridge.',
  },
  {
    id: 'demo-shakshuka',
    title: 'Weeknight shakshuka',
    subtitle: 'with feta and warm bread',
    source: 'Mine',
    servings: 4,
    minutes: 35,
    nutrition: [320, 17, 20, 19, 5, 11, 760],
    tags: ['Vegetarian', 'Weeknight'],
    made: 3,
    ingredients: ['1 onion (diced)', '1 red bell pepper (sliced)', '3 cloves garlic (minced)', '1 tsp ground cumin', '1 tsp smoked paprika', '28 oz canned crushed tomatoes', '6 eggs', '2 oz feta (crumbled)', '¼ cup parsley (chopped)', { item: 'Olive oil', amount: '2 tbsp', pantry: true }, { item: 'Salt and pepper', pantry: true }],
    tools: ['Large skillet with a lid'],
    steps: [
      { title: 'Soften', text: 'Warm the olive oil in a large skillet over medium heat. Cook the onion and pepper 8 minutes, until soft.' },
      { title: 'Spice', text: 'Stir in the garlic, cumin and paprika for 1 minute, until fragrant.' },
      { title: 'Simmer', text: 'Add the tomatoes and a good pinch of salt. Simmer 10 minutes, until thickened.' },
      { title: 'Eggs', text: 'Make 6 wells and crack an egg into each. Cover and cook 5–7 minutes, until the whites are set and the yolks still soft.' },
      { title: 'Finish', text: 'Scatter the feta and parsley over the top and serve straight from the pan with bread.' },
    ],
  },
  {
    id: 'demo-shrimp-tacos',
    title: 'Chili-lime shrimp tacos',
    subtitle: 'with crunchy slaw and lime crema',
    source: 'Meal kit',
    servings: 2,
    minutes: 25,
    nutrition: [610, 34, 58, 26, 7, 8, 1180],
    tags: ['Spicy', 'Quick'],
    fav: 1,
    made: 2,
    ingredients: [
      { item: 'Shrimp', amount: '10 oz', per: { 4: '20 oz' } },
      { item: 'Flour tortillas', amount: '6', per: { 4: '12' } },
      { item: 'Coleslaw mix', amount: '4 oz', per: { 4: '8 oz' } },
      { item: 'Lime', amount: '1', per: { 4: '2' } },
      { item: 'Sour cream', amount: '4 tbsp', per: { 4: '8 tbsp' } },
      { item: 'Chili powder', amount: '2 tsp', per: { 4: '4 tsp' } },
      { item: 'Cilantro', amount: '¼ oz', per: { 4: '½ oz' } },
      { item: 'Neutral oil', amount: '1 tbsp', per: { 4: '2 tbsp' }, pantry: true },
      { item: 'Salt', pantry: true },
    ],
    tools: ['Large pan', 'Small bowl'],
    steps: [
      { title: 'Prep', text: 'Zest and halve the lime. Chop the cilantro. Pat the shrimp dry and toss with the chili powder and a pinch of salt.' },
      { title: 'Crema and slaw', text: 'Stir the sour cream with half the lime zest and a squeeze of lime. Toss the slaw with another squeeze of lime, a pinch of salt and half the cilantro.' },
      { title: 'Shrimp', text: 'Heat the oil in a large pan over medium-high. Cook the shrimp 2–3 minutes a side, until pink. Squeeze over the rest of the lime.' },
      { title: 'Tortillas', text: 'Warm the tortillas in a dry pan, 30 seconds a side.' },
      { title: 'Build', text: 'Fill the tortillas with slaw and shrimp, drizzle with crema, and top with the remaining cilantro.' },
    ],
  },
  {
    id: 'demo-chickpea-curry',
    title: 'Coconut chickpea curry',
    subtitle: 'with spinach and basmati',
    source: 'Family',
    servings: 4,
    minutes: 40,
    nutrition: [520, 16, 66, 22, 12, 8, 690],
    tags: ['Vegetarian', 'Meal prep'],
    made: 4,
    ingredients: ['1 onion (diced)', '3 cloves garlic (minced)', '1 thumb ginger (grated)', '2 tbsp curry powder', '2 cans (15 oz) chickpeas (drained)', '1 can (13.5 oz) coconut milk', '14 oz canned diced tomatoes', '5 oz baby spinach', '1½ cups basmati rice', '1 lime', { item: 'Neutral oil', amount: '2 tbsp', pantry: true }, { item: 'Salt', pantry: true }],
    steps: [
      { title: 'Rice', text: 'Simmer the rice covered in [[2¼ cups]] salted water for 15 minutes, then rest 5 minutes.' },
      { title: 'Base', text: 'Cook the onion in the oil over medium heat for 6 minutes. Add the garlic, ginger and curry powder and stir for 1 minute.' },
      { title: 'Simmer', text: 'Add the chickpeas, coconut milk and tomatoes. Simmer 15 minutes, until thick enough to coat a spoon.' },
      { title: 'Greens', text: 'Stir in the spinach until wilted. Season with salt and a squeeze of lime, and serve over the rice.' },
    ],
    notes: 'Even better the next day. Keeps 4 days in the fridge.',
  },
  {
    id: 'demo-fajitas',
    title: 'Sheet-pan chicken fajitas',
    source: 'Mine',
    servings: 4,
    minutes: 35,
    nutrition: [480, 36, 42, 18, 5, 7, 920],
    tags: ['Weeknight'],
    made: 1,
    ingredients: ['1½ lb chicken breast (sliced into strips)', '3 bell peppers (sliced)', '1 red onion (sliced)', '1 tbsp chili powder', '1 tsp ground cumin', '1 tsp garlic powder', '8 flour tortillas', '1 lime', '1 avocado', { item: 'Olive oil', amount: '3 tbsp', pantry: true }, { item: 'Salt', amount: '1 tsp', pantry: true }],
    tools: ['Sheet pan'],
    steps: [
      { title: 'Heat', text: 'Heat the oven to 425°F.' },
      { title: 'Toss', text: 'Toss the chicken, peppers and onion on a sheet pan with the oil, spices and salt. Spread out in one layer.' },
      { title: 'Roast', text: 'Roast 20–22 minutes, until the chicken is cooked through and the peppers are browned at the edges.' },
      { title: 'Serve', text: 'Squeeze the lime over everything. Serve in warm tortillas with sliced avocado.' },
    ],
  },
  {
    id: 'demo-pancakes',
    title: 'Saturday buttermilk pancakes',
    source: 'Family',
    servings: 4,
    minutes: 25,
    course: 'breakfast',
    nutrition: [410, 11, 58, 14, 2, 14, 690],
    tags: ['Breakfast'],
    made: 9,
    ingredients: ['2 cups flour', '2 tbsp sugar', '2 tsp baking powder', '½ tsp baking soda', '2 cups buttermilk', '2 eggs', '3 tbsp butter (melted)', { item: 'Salt', amount: '½ tsp', pantry: true }, { item: 'Butter for the pan', pantry: true }],
    steps: [
      { title: 'Dry', text: 'Whisk the flour, sugar, baking powder, baking soda and salt in a large bowl.' },
      { title: 'Wet', text: 'Whisk the buttermilk, eggs and melted butter, then fold into the dry mix until just combined. Lumps are fine. Rest 5 minutes.' },
      { title: 'Cook', text: 'Heat a buttered pan over medium. Pour [[¼ cup]] batter per pancake and cook until bubbles cover the top, about 2 minutes; flip and cook 1 minute more.' },
    ],
  },
  {
    id: 'demo-pesto-pasta',
    title: 'Pesto pasta',
    subtitle: 'with chicken, spinach and parmesan',
    source: 'Meal kit',
    servings: 2,
    minutes: 30,
    nutrition: [780, 45, 72, 33, 5, 4, 1040],
    tags: ['Quick'],
    ingredients: [
      { item: 'Penne', amount: '6 oz', per: { 4: '12 oz' } },
      { item: 'Chicken breast', amount: '10 oz', per: { 4: '20 oz' } },
      { item: 'Basil pesto', amount: '4 tbsp', per: { 4: '8 tbsp' } },
      { item: 'Baby spinach', amount: '3 oz', per: { 4: '6 oz' } },
      { item: 'Parmesan', amount: '¼ cup', per: { 4: '½ cup' } },
      { item: 'Lemon', amount: '1', per: { 4: '1' } },
      { item: 'Olive oil', amount: '1 tbsp', per: { 4: '2 tbsp' }, pantry: true },
      { item: 'Salt and pepper', pantry: true },
    ],
    steps: [
      { title: 'Boil', text: 'Bring a large pot of salted water to a boil. Cook the penne 9–11 minutes. Save [[¼ cup]] pasta water, then drain.' },
      { title: 'Chicken', text: 'Season the chicken with salt and pepper. Cook in the oil over medium-high heat 5–7 minutes a side, until cooked through. Rest, then slice.' },
      { title: 'Toss', text: 'In the pasta pot, toss the penne with the pesto, spinach and a splash of pasta water until glossy and the spinach wilts.' },
      { title: 'Serve', text: 'Top with the chicken, parmesan and a squeeze of lemon.' },
    ],
  },
  {
    id: 'demo-steak-potatoes',
    title: 'Steak and crispy potatoes',
    subtitle: 'with garlic green beans',
    source: 'Mine',
    servings: 2,
    minutes: 45,
    nutrition: [720, 46, 48, 36, 7, 4, 860],
    tags: ['Date night'],
    made: 2,
    ingredients: ['1 lb sirloin steak', '1 lb baby potatoes (halved)', '8 oz green beans (trimmed)', '2 cloves garlic (sliced)', '2 sprigs rosemary', '2 tbsp butter', { item: 'Olive oil', amount: '2 tbsp', pantry: true }, { item: 'Salt and pepper', pantry: true }],
    tools: ['Cast-iron skillet', 'Sheet pan'],
    steps: [
      { title: 'Potatoes', text: 'Heat the oven to 425°F. Toss the potatoes with half the oil and salt, cut side down on a sheet pan. Roast 25–30 minutes, until crisp.' },
      { title: 'Steak', text: 'Pat the steak dry and season well. Sear in a very hot cast-iron skillet 3–4 minutes a side for medium-rare, basting with the butter and rosemary for the last minute. Rest 5 minutes.' },
      { title: 'Beans', text: 'In the same pan, cook the green beans and garlic in the rest of the oil for 4–5 minutes, until blistered.' },
      { title: 'Serve', text: 'Slice the steak against the grain and serve with the potatoes and beans, spooning over the pan butter.' },
    ],
  },
];

export function demoBox(today) {
  return {
    version: 1,
    movedIds: [],
    recipes: RECIPES.map((r, i) => normalizeRecipe({ ...r, added: addDays(today, -(i * 9 + 3)), lastMade: r.made ? addDays(today, -(i * 4 + 2)) : undefined })),
  };
}
